name: Discord Webhook

on:
  push:
  release:
    types: [published]
    
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
  
jobs:
  git:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Run Discord Webhook
      uses: johnnyhuy/actions-discord-git-webhook@main
      with:
        webhook_url: https://discord.com/api/webhooks/893407054717419543/907cH3T_lhupUTulBicYBLd5WzmJcqf8mMWOaueaV4aG1aP0XYRsHDE-E0AR6Fhgxf45
